### ISSUE TITLE
panic when running deisrel

### ISSUE THREAD

**Issue by bacongobbler** [deis/deisrel#133]
```
$ deisrel
panic: template: changelog:3: illegal number syntax: "-"

goroutine 1 [running]:
text/template.Must(0x0, 0xca0000, 0xc820066e90, 0x0)
       	/usr/local/go/src/text/template/helper.go:23 +0x4b
github.com/deis/deisrel/changelog.init()
       	/Users/bacongobbler/go/src/github.com/deis/deisrel/changelog/changelog.go:48 +0xc3
github.com/deis/deisrel/actions.init()
       	/Users/bacongobbler/go/src/github.com/deis/deisrel/actions/generate_individual_changelog.go:72 +0x54
main.init()
       	/Users/bacongobbler/go/src/github.com/deis/deisrel/main.go:145 +0x59

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
       	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
```

**Comment by mboersma** [comment]
I get:
```bash
$ deisrel
A params and a repo mapping file is required
```
And I used `deisrel` with great success yesterday to generate changelogs and map out which components needed releasing. Not sure what the difference is though--did you `make bootstrap` before building?

**Comment by mboersma** [comment]
Turns out `deisrel` needs to be built with Go 1.6 or later, which is a reasonable requirement for an in-house build tool.
